-- INSERT INTO CIDADE (NOME,IBGE,ESTADO_ID) VALUES ('MANAUS','1302603',1);
-- INSERT INTO CIDADE (NOME,IBGE,ESTADO_ID) VALUES ('IRANDUBA','1301852',1);

INSERT INTO PAIS (ID, NOME) VALUES (0, 'Brasil');

INSERT INTO CIDADE (ID, NOME, PAIS_ID) VALUES (0, 'Brasilia', 0);
